language: rust
rust:
  # - stable
  # - beta
  - nightly
  env: RUSTFMT=1
matrix:
  # allow_failures:
  #   - rust: nightly
  fast_finish: true
cache: cargo

before_script:
  - if [ "$RUSTFMT" = 1 ]; then rustup component add rustfmt; fi

script:
  - if [ "$RUSTFMT" = 1 ]; then cargo fmt -- --check; fi
  - cargo build --all
  - cargo test -- --nocapture