[package]
name = "pearl"
version = "0.1.0"
description = "low level blob-based I/O library"
authors = ["Pavel Yakushin <p.yakushin@qoollo.com>"]
edition = "2018"
repository = "https://lab.qoollo.com/py/pearl"
readme = "README.md"

[dependencies]
env_logger = "0.6.0"
log = "0.4.6"
futures-preview = "0.3.0-alpha.13"
serde = "1.0.89"
serde_derive = "1.0.89"
bincode = "1.1.2"