[package]
name = "pearl"
version = "0.1.0"
description = "low level blob-based I/O library"
authors = ["Pavel Yakushin <p.yakushin@qoollo.com>"]
edition = "2018"
repository = "https://lab.qoollo.com/py/pearl"
readme = "README.md"

[dependencies]
bincode = "1.1"
chrono = "0.4"
crc = "1.8"
env_logger = "0.6"
log = "0.4"
rand = "0.7"
serde = "1.0"
serde_derive = "1.0"
futures-preview = { version = "0.3.0-alpha.19" }
tokio = { version = "0.2.0-alpha.6" }

clap = { version = "2.33", optional = true }

[features]
benchmark = ["clap"]

[lib]
name = "pearl"

[[bin]]
name = "benchmark"
path = "src/benchmark/bin.rs"
required-features = ["benchmark"]