[package]
name = "pearl"
version = "0.1.0"
description = "low level blob-based I/O library"
authors = ["Pavel Yakushin <p.yakushin@qoollo.com>"]
edition = "2018"
repository = "https://lab.qoollo.com/py/pearl"
readme = "README.md"

[dependencies]
env_logger = "*"
log = "*"
futures-preview = { version = "0.3.0-alpha.16", features = ["compat"] }
serde = "*"
serde_derive = "*"
bincode = "*"
rand = "*"
tokio = "*"
color-backtrace = "*"

runtime = { git = "https://github.com/rustasync/runtime", optional = true }
clap = { version = "*", optional = true }

[features]
benchmark = ["clap", "runtime"]

[lib]
name = "pearl"

# [[bin]]
# name = "benchmark"
# path = "src/benchmark/bin.rs"
# required-features = ["benchmark"]