name: tests

on:
  pull_request:
      types: [ opened, synchronize, reopened, ready_for_review ]
  push:
    branches: [ master, 113-setup-build-and-test-with-github-actions]
    
jobs:

  tests:
    runs-on: ubuntu-latest
    container: rust:1.53.0
    steps:
      - name: Checks-out repository 
        uses: actions/checkout@v2
      - name: Install latest nightly 
        uses: actions-rs/toolchain@v1
        with:                                                                                                                     toolchain: nightly                                                                                                      default: true
      - name: Tests
        run: |
          export PEARL_COMMIT_HASH=$(echo ${GITHUB_SHA} | cut -c1-8)
          cargo test
